### ISSUE TITLE
linux/arm/v8 - compatibility

### ISSUE THREAD

**Issue by rafinhaa** [apyos/docker-3cx-sbc#2]
Can we make it compatible with arm v8 architecture?

**Comment by filoozom** [comment]
I'm afraid not, 3CX isn't interested at all in providing `arm64` binaries, and of course the code is closed source. Believe me, I've tried. You can find a ton of similar requests with a quick forum search: https://www.3cx.com/community/search/2008238/?q=arm64&o=date.

The PBX is available on `arm64`, but the SBC only on `amd64` and `armhf`.
